function [fitresult, gof] = ETempfit(EN, a)
%CREATEFIT(EN,A)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : EN
%      Y Output: a
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Dec-2020 22:10:53


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( EN, a );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'a vs. EN', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel EN
% ylabel a
grid on


